// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy73TlciQbBXBfYsOVuHtuyj1j0aPlKrM',
    appId: '1:272232665259:web:848f4dd8498008d028e7ee',
    messagingSenderId: '272232665259',
    projectId: 'chessmasteryapp',
    authDomain: 'chessmasteryapp.firebaseapp.com',
    storageBucket: 'chessmasteryapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFsMmZeumGwjFsQ707fu93Ukbl8UOvhZE',
    appId: '1:272232665259:android:0d9858b4aecfc70028e7ee',
    messagingSenderId: '272232665259',
    projectId: 'chessmasteryapp',
    storageBucket: 'chessmasteryapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPlXhhs9duQDHsxZOLzMPAXDVEoMa0XUU',
    appId: '1:272232665259:ios:13a32da3d5f4144a28e7ee',
    messagingSenderId: '272232665259',
    projectId: 'chessmasteryapp',
    storageBucket: 'chessmasteryapp.appspot.com',
    iosBundleId: 'com.example.chessapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPlXhhs9duQDHsxZOLzMPAXDVEoMa0XUU',
    appId: '1:272232665259:ios:13a32da3d5f4144a28e7ee',
    messagingSenderId: '272232665259',
    projectId: 'chessmasteryapp',
    storageBucket: 'chessmasteryapp.appspot.com',
    iosBundleId: 'com.example.chessapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBy73TlciQbBXBfYsOVuHtuyj1j0aPlKrM',
    appId: '1:272232665259:web:7d29a052259bfe0c28e7ee',
    messagingSenderId: '272232665259',
    projectId: 'chessmasteryapp',
    authDomain: 'chessmasteryapp.firebaseapp.com',
    storageBucket: 'chessmasteryapp.appspot.com',
  );
}
